apiVersion: v1
kind: Service
metadata:
  name: ramcapstoneproject
  labels:
      app: ramcapstoneproject
spec:
  type: LoadBalancer
  selector:
    app: ramcapstoneproject
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80